/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NButton: typeof import('nvcui')['NButton']
    NInput: typeof import('nvcui')['NInput']
    NSpace: typeof import('nvcui')['NSpace']
    NTable: typeof import('nvcui')['NTable']
    NTableColumn: typeof import('nvcui')['NTableColumn']
    NTooltip: typeof import('nvcui')['NTooltip']
    NVirtualList: typeof import('nvcui')['NVirtualList']
  }
}
