/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NButton: typeof import('nui')['NButton']
    NInput: typeof import('nui')['NInput']
    NSpace: typeof import('nui')['NSpace']
    NTooltip: typeof import('nui')['NTooltip']
    NVirtualList: typeof import('nui')['NVirtualList']
  }
}
